# board_qemu_a.conf
# 针对 QEMU 平台 board_qemu_a 定义变量
export BOARD_NAME=board_qemu_a

export LINUX_LOCAL_VERSION=6.1

# 配置文件路径
#export KERNEL_DEFCONFIG="$PROJECT_ROOT/board/board_qemu_a/linux-$LINUX_LOCAL_VERSION/configs/kernel_defconfig"
export KERNEL_DEFCONFIG="quantum_qemu"
export UBOOT_DEFCONFIG="quantum_qemu_arm64_uboot"
export BUILDROOT_DEFCONFIG="buildroot_defconfig"
export KERNEL_DTB_NAME="quantum/quantum_qemu"

# 板卡特定参数
export KERNEL_ARCH=arm64
export UBOOT_ARCH=arm64
export QEMU_MACHINE=virt
export QEMU_CPU=cortex-a57
export QEMU_SMP=4
export QEMU_MEM=1024
export KERNEL_CMDLINE="console=ttyAMA0 root=/dev/ram0 rw init=/linuxrc nokaslr earlycon=pl011,0x9000000 debug loglevel=8"

# BOARD_DIR 目录
export BOARD_DIR="$PROJECT_ROOT/board/board_qemu_a"

# 输出目录
export BOARD_OUT_DIR="$OUT_DIR/board_qemu_a"
# BR2_EXTERNAL 目录
export BR2_EXTERNAL_DIR="$PROJECT_ROOT/board/board_qemu_a/br2_external"
