# board_qemu_b.conf
# 针对 QEMU 平台 board_qemu_b 定义变量
BOARD_NAME=board_qemu_b

# 配置文件路径
KERNEL_DEFCONFIG="$PROJECT_ROOT/board/board_qemu_b/config/kernel_defconfig"
UBOOT_DEFCONFIG="$PROJECT_ROOT/board/board_qemu_b/config/uboot_defconfig"
BUILDROOT_DEFCONFIG="$PROJECT_ROOT/board/board_qemu_b/config/buildroot_defconfig"

# 板卡特定参数
KERNEL_ARCH=arm64
UBOOT_ARCH=arm64
QEMU_MACHINE=virt
QEMU_CPU=cortex-a57
QEMU_SMP=2
QEMU_MEM=2048
KERNEL_CMDLINE="console=ttyAMA0 root=/dev/vda rw nokaslr preempt loglevel=7"

# 输出目录
BOARD_OUT_DIR="$OUT_DIR/board_qemu_b"
